//
//  CoinDescription.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class CoinDescription: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _vote: NSNumber?
    var _age: NSNumber?
    var _backgroundImage: String?
    var _category: String?
    var _logoImage: String?
    var _name: String?
    var _sign: String?
    var _type: String?
    
    class func dynamoDBTableName() -> String {

        return "pollingstation-mobilehub-1632318331-Coin-Description"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_vote"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_vote" : "vote",
               "_age" : "age",
               "_backgroundImage" : "background_image",
               "_category" : "category",
               "_logoImage" : "logo_image",
               "_name" : "name",
               "_sign" : "sign",
               "_type" : "type",
        ]
    }
}
